import { describe, it, expect, beforeAll, afterAll, vi } from 'vitest';
import request from 'supertest';
import fc from 'fast-check';
import app from '../../src/app';
import express, { Request, Response, NextFunction } from 'express';
import { errorHandler } from '../../src/middlewares/errorHandler';

/**
 * Property-based tests for credential security.
 * Property 3: Variables de entorno no expuestas en respuestas.
 *
 * **Validates: Requirements 10.2, 10.6**
 *
 * For ANY response generated by the API in production mode,
 * sensitive environment variable values (DB_PASSWORD, JWT_SECRET)
 * must NEVER appear in the response body.
 */

// Generator for sensitive-looking secret values (random passwords/tokens)
const sensitiveValue = fc
  .tuple(
    fc.stringOf(fc.constantFrom(...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('')), {
      minLength: 2,
      maxLength: 4,
    }),
    fc.stringOf(fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz'.split('')), {
      minLength: 2,
      maxLength: 4,
    }),
    fc.stringOf(fc.constantFrom(...'0123456789'.split('')), {
      minLength: 2,
      maxLength: 4,
    }),
    fc.stringOf(fc.constantFrom(...'!@#$%^&*_+-='.split('')), {
      minLength: 1,
      maxLength: 3,
    })
  )
  .map(([upper, lower, digits, special]) => upper + lower + digits + special);

// Generator for JWT-like secrets (long alphanumeric strings)
const jwtSecretValue = fc.stringOf(
  fc.constantFrom(
    ...'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'.split(
      ''
    )
  ),
  { minLength: 32, maxLength: 64 }
);

describe('Property 3: Variables de entorno no expuestas en respuestas', () => {
  let originalNodeEnv: string | undefined;
  let originalDbPassword: string | undefined;
  let originalJwtSecret: string | undefined;

  beforeAll(() => {
    originalNodeEnv = process.env.NODE_ENV;
    originalDbPassword = process.env.DB_PASSWORD;
    originalJwtSecret = process.env.JWT_SECRET;
  });

  afterAll(() => {
    process.env.NODE_ENV = originalNodeEnv;
    process.env.DB_PASSWORD = originalDbPassword;
    process.env.JWT_SECRET = originalJwtSecret;
  });

  describe('Production error responses never contain DB_PASSWORD', () => {
    /**
     * **Validates: Requirements 10.2, 10.6**
     *
     * For any randomly generated DB_PASSWORD value, when an unhandled error
     * occurs in production that contains the password in its message,
     * the API response body must NOT contain the password value.
     */
    it('unhandled errors with DB_PASSWORD in message never leak it in production response', async () => {
      await fc.assert(
        fc.asyncProperty(sensitiveValue, async (dbPassword) => {
          process.env.NODE_ENV = 'production';
          process.env.DB_PASSWORD = dbPassword;

          // Create a minimal express app with a route that throws an error containing the secret
          const testApp = express();
          testApp.get('/api/test-error', (_req: Request, _res: Response) => {
            throw new Error(
              `Connection failed: password=${dbPassword} host=db.example.com`
            );
          });
          testApp.use(errorHandler);

          const response = await request(testApp).get('/api/test-error');

          // The response body (stringified) must never contain the DB_PASSWORD
          const responseBody = JSON.stringify(response.body);
          expect(responseBody).not.toContain(dbPassword);
          expect(response.status).toBe(500);
          expect(response.body.message).toBe('Error interno del servidor');
        }),
        { numRuns: 50 }
      );
    });
  });

  describe('Production error responses never contain JWT_SECRET', () => {
    /**
     * **Validates: Requirements 10.2, 10.6**
     *
     * For any randomly generated JWT_SECRET value, when an unhandled error
     * occurs in production that contains the secret in its message,
     * the API response body must NOT contain the secret value.
     */
    it('unhandled errors with JWT_SECRET in message never leak it in production response', async () => {
      await fc.assert(
        fc.asyncProperty(jwtSecretValue, async (jwtSecret) => {
          process.env.NODE_ENV = 'production';
          process.env.JWT_SECRET = jwtSecret;

          const testApp = express();
          testApp.get('/api/test-error', (_req: Request, _res: Response) => {
            throw new Error(
              `JWT verification failed with secret: ${jwtSecret}`
            );
          });
          testApp.use(errorHandler);

          const response = await request(testApp).get('/api/test-error');

          const responseBody = JSON.stringify(response.body);
          expect(responseBody).not.toContain(jwtSecret);
          expect(response.status).toBe(500);
          expect(response.body.message).toBe('Error interno del servidor');
        }),
        { numRuns: 50 }
      );
    });
  });

  describe('Production API endpoints never expose secrets in responses', () => {
    /**
     * **Validates: Requirements 10.2, 10.6**
     *
     * For any randomly generated DB_PASSWORD and JWT_SECRET, when making
     * requests to real API endpoints (including ones that trigger errors),
     * the response body must never contain those secret values.
     */
    it('real API error responses (401, 400) never contain env secrets', async () => {
      await fc.assert(
        fc.asyncProperty(
          sensitiveValue,
          jwtSecretValue,
          async (dbPassword, jwtSecret) => {
            process.env.NODE_ENV = 'production';
            process.env.DB_PASSWORD = dbPassword;
            process.env.JWT_SECRET = jwtSecret;

            // Test various API endpoints that generate error responses
            const endpoints = [
              { method: 'get' as const, path: '/api/auth/me' },
              { method: 'get' as const, path: '/api/users' },
              { method: 'get' as const, path: '/api/clients' },
              {
                method: 'post' as const,
                path: '/api/auth/login',
                body: { email: 'fake@test.com', password: 'wrong' },
              },
            ];

            for (const endpoint of endpoints) {
              let response;
              if (endpoint.method === 'post' && endpoint.body) {
                response = await request(app)
                  .post(endpoint.path)
                  .send(endpoint.body);
              } else {
                response = await request(app).get(endpoint.path);
              }

              const responseText = JSON.stringify(response.body) + (response.text || '');
              expect(responseText).not.toContain(dbPassword);
              expect(responseText).not.toContain(jwtSecret);
            }
          }
        ),
        { numRuns: 20 }
      );
    });
  });

  describe('Error with both secrets in stack trace never leaks in production', () => {
    /**
     * **Validates: Requirements 10.2, 10.6**
     *
     * For any combination of DB_PASSWORD and JWT_SECRET values in an error
     * stack trace, the production response must never expose either value.
     */
    it('error containing both secrets in message and stack is sanitized in production', async () => {
      await fc.assert(
        fc.asyncProperty(
          sensitiveValue,
          jwtSecretValue,
          async (dbPassword, jwtSecret) => {
            process.env.NODE_ENV = 'production';
            process.env.DB_PASSWORD = dbPassword;
            process.env.JWT_SECRET = jwtSecret;

            const testApp = express();
            testApp.get('/api/test-error', (_req: Request, _res: Response) => {
              const err = new Error(
                `Config dump: DB_PASSWORD=${dbPassword}, JWT_SECRET=${jwtSecret}`
              );
              throw err;
            });
            testApp.use(errorHandler);

            const response = await request(testApp).get('/api/test-error');

            const fullResponse = JSON.stringify(response.body);
            expect(fullResponse).not.toContain(dbPassword);
            expect(fullResponse).not.toContain(jwtSecret);
            expect(response.body).not.toHaveProperty('stack');
            expect(response.status).toBe(500);
          }
        ),
        { numRuns: 30 }
      );
    });
  });
});
